### ISSUE TITLE
Outdated Python version incompatible with Certbot 3.0

### ISSUE THREAD

**Issue by chaosyoga** [chaptergy/certbot-dns-njalla#11]
The following plugins are using an outdated python version and must be updated to be compatible with Certbot 3.0. Please see https://community.letsencrypt.org/t/certbot-3-0-could-have-potential-third-party-snap-breakages/226940 for more information:
  * certbot-dns-njalla

Temporary solution: `sudo snap revert certbot --revision 3834 `

**Comment by chaptergy** [comment]
The new [2.0.0 release](https://github.com/chaptergy/certbot-dns-njalla/releases/tag/V2.0.0) updates to certbot 3.
