### ISSUE TITLE
403: Permission denied error

### ISSUE THREAD

**Issue by parhammhd** [chaptergy/certbot-dns-njalla#13]
I get this message when trying to renew my domains even though my api token has no restriction for testing purposes.

Unexpected error determining zone identifier for example.org: 403: Permission denied.

I am using certbot 3.0.1 with the latest version of the plugin.

Previously I was using HTTP-01 but I want to switch to DNS-01.

My renewal command is this in case that is the issue :
certbot renew --dry-run -a dns-njalla --dns-njalla-credentials /etc/letsencrypt/njalla.ini

**Comment by chaptergy** [comment]
That's because `example.org` is not a domain you have in your Njalla account. You need to use the correct domain.

If `example.org` is just for privacy purposes, make sure you use a domain you have actually created in njalla. It does not work for domains, which do not exist.

**Comment by chaptergy** [comment]
On deeper inspection there were some problems with subdomains because of some [changes in certbot](https://github.com/certbot/certbot/pull/9821). They are now fixed in [v2.0.2](https://github.com/chaptergy/certbot-dns-njalla/releases/tag/v2.0.2)
