### ISSUE TITLE
Do not recommend installing globally with Pip

### ISSUE THREAD

**Issue by faivirol** [chaptergy/certbot-dns-njalla#14]
Installing Python packages globally is dangerous. I would suggest changing the README to recommend [pipx](https://github.com/pypa/pipx) instead like:

```shell
$ sudo apt install pipx
$ pipx ensurepath
$ pipx install certbot
$ pipx inject certbot certbot-dns-njalla
```

It can be used directly with `$ certbot ...` as if installed globally.

**Comment by chaptergy** [comment]
I've updated the readme to reference the python environment which is used in the official certbot setup instructions.
