### ISSUE TITLE
Document or change Snap channel

### ISSUE THREAD

**Issue by faivirol** [chaptergy/certbot-dns-njalla#15]
I have little experience with Snap, so was confused why `snap install certbot-dns-njalla` was not enough. `certbot` is on >3.0.0 even on stable, but this plugin only supports it in edge. I stopped using Snap instead of solving the issue, but it's probably an easy fix to either add to the README or push a version to stable that's compatible with certbot's stable channel.

**Comment by chaptergy** [comment]
As I am not familiar with snap either, I did not realize that a built snap is only available on an edge channel, and needs to be manually promoted to stable for it to be available normally. It will now download the newest version.

**Comment by faivirol** [comment]
Thanks for your work ❤️
