### ISSUE TITLE
Provide Snap package

### ISSUE THREAD

**Issue by TheGroundZero** [chaptergy/certbot-dns-njalla#2]
Certbot's user guide recommends installating Certbot via Snap (see e.g. https://certbot.eff.org/instructions?ws=other&os=debian-10).
However, the plugin for Njalla is not available on Snap (yet), thus requesting a certicate for a Njalla domain is not possible using this installation method.

**Comment by TheGroundZero** [comment]
```bash
snap install core
snap refresh core
snap install --classic certbot

pip3 install certbot-dns-njalla

cat njalla.ini
# dns_njalla_token=<TOKEN>
```

```bash
# certbot certonly -a dns-njalla --dns-njalla-credentials /root/njalla.ini -d *.mydomain.tld -d mydomain.tld
usage:
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate.
certbot: error: unrecognized arguments: --dns-njalla-credentials /root/njalla.ini
```

```bash
# certbot certonly -a dns-njalla -d *.mydomain.tld -d mydomain.tld
Saving debug log to /var/log/letsencrypt/letsencrypt.log
The requested dns-njalla plugin does not appear to be installed
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
```

**Comment by chaptergy** [comment]
Unfortunately due to the limited documentation provided by certbot on how to create the snap file, I am unable to do so since I am stuck on a missing `snap-constraints.txt`, for which I honestly don't really understand the circumstances. If someone is able to provide a working workflow to create a snap file which works with certbot as a PR, I will gladly merge it and publish it as a snap. Until then I have already put too much time into trying to create a snap to no avail.

**Comment by chaptergy** [comment]
Okay, I have managed to get it to compile, and everything seems to work fine for me using snap now.

**Comment by Nemesis77swe** [comment]
I'm a noob, but I stumbled upon these pages regarding plugin and snap

[https://eff-certbot.readthedocs.io/en/stable/contributing.html#building-snaps]() 

[https://eff-certbot.readthedocs.io/en/stable/contributing.html#writing-your-own-plugin-snap]() 

maybe they can solve the snap plugin issue?

**Comment by chaptergy** [comment]
Yeah, that's the documentation I initially tried to use. However it did not really work out of the box for me. And the documentation stays a little surface level to make it easy to debug why. But after some more tinkering today and removing some stuff from the suggested script it does seem to work now.

**Comment by Nemesis77swe** [comment]
Well, that's great news, looking forward to test it!
