### ISSUE TITLE
tag a recent release

### ISSUE THREAD

**Issue by catdevnull** [chaptergy/certbot-dns-njalla#7]
hi! i'm packaging this for alpine linux and was asked to base the package on an actual release. could you please tag a recent commit? thanks!

https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/45409#note_303125

**Comment by chaptergy** [comment]
Sorry for the delay. I created a new release on the latest commit. I hope this is what you meant.
https://github.com/chaptergy/certbot-dns-njalla/releases/tag/v1.0.1

**Comment by catdevnull** [comment]
yes, thank you! https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/47165
