### ISSUE TITLE
Question: Required API methods

### ISSUE THREAD

**Issue by TheGroundZero** [chaptergy/certbot-dns-njalla#9]
Following the principle of Least Privilege, it'd be a good idea to list the required API methods for this plugin to function.
That way, users can be instructed to limit the access of the API key to the necessary methods.

API methods can be found here: https://njal.la/api/

**Comment by chaptergy** [comment]
Just to start documenting here, it seems like the following api methods are the only ones required:

```
add-record
remove-record
```

with record type


```
TXT
```

Domains and record prefixes would be unique to your use case.   
I have not yet checked whether the information above is correct, it is just my current assumption.

**Comment by chaptergy** [comment]
The required methods are as of [v2.0.2](https://github.com/chaptergy/certbot-dns-njalla/releases/tag/v2.0.2) documented in the readme.
